//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PopulateDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class testetlb
    {
        public int code { get; set; }
        public string string1 { get; set; }
        public string string2 { get; set; }
    }
}
